{% set name = "kdepy" %}
{% set version = "1.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/KDEpy-{{ version }}.tar.gz
  sha256: d26f24c7886e341be6a414e226250f0ae2d6059e8fecaf32ad1f66699ca7a1ae

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=45
    - wheel
    - cython >=0.29,<3.0.0
    - numpy >=1.14.2,<2.0.0
    - pip
  run:
    - python
    - scipy >=1.0.1
    - matplotlib-base >=2.2.2
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - KDEpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tommyod/KDEpy
  summary: Kernel Density Estimation in Python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davecwright3
