{% set name = "kdepy" %}
{% set version = "1.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/KDEpy-{{ version }}.tar.gz
  sha256: 4bf0b2afd430ce5b40fafd98144de83d8b715d46fdf0f45fed2b5c2e9c40ce46

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=45
    - wheel
    - cython >=0.29,<3.0.0
    - numpy >=1.14.2,<2.0.0
    - pip
  run:
    - python
    - scipy >=1.0.1
    - matplotlib-base >=2.2.2
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - KDEpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tommyod/KDEpy
  summary: Kernel Density Estimation in Python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davecwright3
