{% set name = "kdepy" %}
{% set version = "1.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tommyod/KDEpy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 03052f5b30e8f5b1fee129099c9082ff225a0da7c0650614693af3fb2d274ff1

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0,<4.0                      # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=45
    - wheel
    - cython >=3.0,<4.0
    - numpy
    - pip
  run:
    - python
    - scipy >=1.0.1
    - matplotlib-base >=2.2.2
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - KDEpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tommyod/KDEpy
  summary: Kernel Density Estimation in Python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davecwright3
    - ken-lauer
