{% set name = "kdepy" %}
{% set version = "1.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 603cc3cd1c80bb0a7a9b0b74ebae117d312e37cee8fc1c637b46888e48d91085
  patches:
    # pyx file is missing in PyPI release, but pre-Cythonized C file exists;
    # patch to build with this for now.
    - patches/0001-fix-missing-pyx-file.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29,<3.0.0                   # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=45
    - wheel
    - cython >=0.29,<3.0.0
    - numpy
    - pip
  run:
    - python
    - scipy >=1.0.1
    - matplotlib-base >=2.2.2
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - KDEpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tommyod/KDEpy
  summary: Kernel Density Estimation in Python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davecwright3
    - ken-lauer
